project:
  type: website
  output-dir: www/
  execute-dir: project
  lib-dir: site_libs

format:
  html:
    include-after-body:
      - language_switcher_js.html
    theme:
      dark: darkly
      light: flatly
editor: source

website:
  page-navigation: true
  reader-mode: false
  search: false
  navbar:
    pinned: false
  bread-crumbs: false
