project:
  output-dir: www/en

metadata-files:
  - _metadata-en.yml

website:
  site-path: "/en/"
  title: "Listings with profiles"
  navbar:
    left:
      - text: Home
        href: index.qmd
    right:
      - href: "#lang-switcher"
        text: Français
