project:
  output-dir: www/en

metadata-files:
  - _metadata-en.yml

website:
  site-path: "/en/"
  sidebar:
      title: "Countries"
      style: "floating"
      search: false
      collapse-level: 1
      contents:
        - index.qmd
        - section: "Africa"
          contents:
            - auto: "Africa/*.qmd"
        - section: "Middle East and North Africa"
          contents:
            - auto: "MENA/*.qmd"
  navbar:
    right:
      - href: "#lang-switcher"
        text: Français
    left:
      - text: "Documents"
        href: documents.qmd
