project:
  output-dir: www/fr

metadata-files:
  - _metadata-fr.yml

website:
  site-path: "/fr/"
  title: "Listes avec profils"
  navbar:
    left:
      - text: Maison
        href: index.qmd
    right:
      - href: "#lang-switcher"
        text: English
